name: shiki_flutter_workspace

publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - packages/shiki_flutter_engine_interface
  - packages/shiki_flutter
  - packages/shiki_flutter_native_engine
  - packages/shiki_flutter_dart_engine
  - website
