// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../core/code_language.dart';
import 'angular_expression.dart';

/// angular-let-declaration grammar (scope `template.let.ng`).
const CodeLanguage angularLetDeclaration = CodeLanguage(
  id: 'angular-let-declaration',
  scopeName: 'template.let.ng',
  displayName: 'angular-let-declaration',
  json: _json,
  embeddedLanguages: _embedded,
);

List<CodeLanguage> _embedded() => [angularExpression];

const _json =
    '{"injectTo":["text.html.derivative","text.html.derivative.ng","source.ts.ng"],"injectionSelector":"L:text.html -comment -expression.ng -meta.tag -source.css -source.js","name":"angular-let-declaration","patterns":[{"include":"#letDeclaration"}],"repository":{"letDeclaration":{"begin":"(@let)\\\\s+([\$_[:alpha:]][\$_[:alnum:]]*)\\\\s*(=)?","beginCaptures":{"1":{"name":"storage.type.ng"},"2":{"name":"variable.other.constant.ng"},"3":{"name":"keyword.operator.assignment.ng"}},"end":"(?<=;)","name":"meta.definition.variable.ng","patterns":[{"include":"#letInitializer"}]},"letInitializer":{"begin":"\\\\s*","beginCaptures":{"0":{"name":"keyword.operator.assignment.ng"}},"contentName":"meta.definition.variable.initializer.ng","end":";","endCaptures":{"0":{"name":"punctuation.terminator.statement.ng"}},"patterns":[{"include":"expression.ng"}]}},"scopeName":"template.let.ng"}';
