// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../core/code_language.dart';
import 'angular_expression.dart';

/// angular-template grammar (scope `template.ng`).
const CodeLanguage angularTemplate = CodeLanguage(
  id: 'angular-template',
  scopeName: 'template.ng',
  displayName: 'angular-template',
  json: _json,
  embeddedLanguages: _embedded,
);

List<CodeLanguage> _embedded() => [angularExpression];

const _json =
    '{"injectTo":["text.html.derivative","text.html.derivative.ng","source.ts.ng"],"injectionSelector":"L:text.html -comment","name":"angular-template","patterns":[{"include":"#interpolation"}],"repository":{"interpolation":{"begin":"\\\\{\\\\{","beginCaptures":{"0":{"name":"punctuation.definition.block.ts"}},"contentName":"expression.ng","end":"}}","endCaptures":{"0":{"name":"punctuation.definition.block.ts"}},"patterns":[{"include":"expression.ng"}]}},"scopeName":"template.ng"}';
