// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../core/code_language.dart';
import 'html.dart';
import 'angular_expression.dart';
import 'angular_let_declaration.dart';
import 'angular_template.dart';
import 'angular_template_blocks.dart';

/// Angular HTML grammar (scope `text.html.derivative.ng`).
const CodeLanguage angularHtml = CodeLanguage(
  id: 'angular-html',
  scopeName: 'text.html.derivative.ng',
  displayName: 'Angular HTML',
  json: _json,
  embeddedLanguages: _embedded,
  categories: [GrammarCategory.web],
);

List<CodeLanguage> _embedded() => [
  html,
  angularExpression,
  angularLetDeclaration,
  angularTemplate,
  angularTemplateBlocks,
];

const _json =
    '{"displayName":"Angular HTML","injections":{"R:text.html - (comment.block, text.html meta.embedded, meta.tag.*.*.html, meta.tag.*.*.*.html, meta.tag.*.*.*.*.html)":{"patterns":[{"match":"<","name":"invalid.illegal.bad-angle-bracket.html"}]}},"name":"angular-html","patterns":[{"include":"text.html.basic#core-minus-invalid"},{"begin":"(</?)(\\\\w[^>\\\\s]*)(?<!/)","beginCaptures":{"1":{"name":"punctuation.definition.tag.begin.html"},"2":{"name":"entity.name.tag.html"}},"end":"((?: ?/)?>)","endCaptures":{"1":{"name":"punctuation.definition.tag.end.html"}},"name":"meta.tag.other.unrecognized.html.derivative","patterns":[{"include":"text.html.basic#attribute"}]}],"scopeName":"text.html.derivative.ng"}';
