// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../core/code_language.dart';

/// CSV grammar (scope `text.csv`).
const CodeLanguage csv = CodeLanguage(
  id: 'csv',
  scopeName: 'text.csv',
  displayName: 'CSV',
  json: _json,
  categories: [GrammarCategory.data],
);

const _json =
    '{"displayName":"CSV","fileTypes":["csv"],"name":"csv","patterns":[{"captures":{"1":{"name":"rainbow1"},"10":{"name":"invalid.rainbow10"},"2":{"name":"keyword.rainbow2"},"3":{"name":"entity.name.function.rainbow3"},"4":{"name":"comment.rainbow4"},"5":{"name":"string.rainbow5"},"6":{"name":"variable.parameter.rainbow6"},"7":{"name":"constant.numeric.rainbow7"},"8":{"name":"entity.name.type.rainbow8"},"9":{"name":"markup.bold.rainbow9"}},"match":"( *\\"(?:[^\\"]*\\"\\")*[^\\"]*\\" *(?:,|\$)|[^,]*(?:,|\$))?( *\\"(?:[^\\"]*\\"\\")*[^\\"]*\\" *(?:,|\$)|[^,]*(?:,|\$))?( *\\"(?:[^\\"]*\\"\\")*[^\\"]*\\" *(?:,|\$)|[^,]*(?:,|\$))?( *\\"(?:[^\\"]*\\"\\")*[^\\"]*\\" *(?:,|\$)|[^,]*(?:,|\$))?( *\\"(?:[^\\"]*\\"\\")*[^\\"]*\\" *(?:,|\$)|[^,]*(?:,|\$))?( *\\"(?:[^\\"]*\\"\\")*[^\\"]*\\" *(?:,|\$)|[^,]*(?:,|\$))?( *\\"(?:[^\\"]*\\"\\")*[^\\"]*\\" *(?:,|\$)|[^,]*(?:,|\$))?( *\\"(?:[^\\"]*\\"\\")*[^\\"]*\\" *(?:,|\$)|[^,]*(?:,|\$))?( *\\"(?:[^\\"]*\\"\\")*[^\\"]*\\" *(?:,|\$)|[^,]*(?:,|\$))?( *\\"(?:[^\\"]*\\"\\")*[^\\"]*\\" *(?:,|\$)|[^,]*(?:,|\$))?","name":"rainbowgroup"}],"scopeName":"text.csv"}';
