// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../core/code_language.dart';
import 'html.dart';

/// HTML (Derivative) grammar (scope `text.html.derivative`).
const CodeLanguage htmlDerivative = CodeLanguage(
  id: 'html-derivative',
  scopeName: 'text.html.derivative',
  displayName: 'HTML (Derivative)',
  json: _json,
  embeddedLanguages: _embedded,
  categories: [GrammarCategory.web, GrammarCategory.markup],
);

List<CodeLanguage> _embedded() => [html];

const _json =
    '{"displayName":"HTML (Derivative)","injections":{"R:text.html - (comment.block, text.html meta.embedded, meta.tag.*.*.html, meta.tag.*.*.*.html, meta.tag.*.*.*.*.html)":{"patterns":[{"match":"<","name":"invalid.illegal.bad-angle-bracket.html"}]}},"name":"html-derivative","patterns":[{"include":"text.html.basic#core-minus-invalid"},{"begin":"(</?)(\\\\w[^<>\\\\s]*)(?<!/)","beginCaptures":{"1":{"name":"punctuation.definition.tag.begin.html"},"2":{"name":"entity.name.tag.html"}},"end":"((?: ?/)?>)","endCaptures":{"1":{"name":"punctuation.definition.tag.end.html"}},"name":"meta.tag.other.unrecognized.html.derivative","patterns":[{"include":"text.html.basic#attribute"}]}],"scopeName":"text.html.derivative"}';
