// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../core/code_language.dart';
import 'html.dart';

/// jinja-html grammar (scope `text.html.jinja`).
const CodeLanguage jinjaHtml = CodeLanguage(
  id: 'jinja-html',
  scopeName: 'text.html.jinja',
  displayName: 'jinja-html',
  json: _json,
  embeddedLanguages: _embedded,
);

List<CodeLanguage> _embedded() => [html];

const _json =
    '{"displayName":"jinja-html","firstLineMatch":"^\\\\{% extends [\\"\'][^\\"\']+[\\"\'] %}","foldingStartMarker":"(<(?i:(head|table|tr|div|style|script|ul|ol|form|dl))\\\\b.*?>|\\\\{%\\\\s*(block|filter|for|if|macro|raw))","foldingStopMarker":"(</(?i:(head|table|tr|div|style|script|ul|ol|form|dl))\\\\b.*?>|\\\\{%\\\\s*(end(?:block|filter|for|if|macro|raw))\\\\s*%})","name":"jinja-html","patterns":[{"include":"source.jinja"},{"include":"text.html.basic"}],"scopeName":"text.html.jinja"}';
