// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../core/code_language.dart';
import 'shellscript.dart';

/// Shell Session grammar (scope `text.shell-session`).
const CodeLanguage shellsession = CodeLanguage(
  id: 'shellsession',
  scopeName: 'text.shell-session',
  displayName: 'Shell Session',
  json: _json,
  embeddedLanguages: _embedded,
  aliases: ['console'],
  categories: [GrammarCategory.scripting],
);

List<CodeLanguage> _embedded() => [shellscript];

const _json =
    '{"displayName":"Shell Session","fileTypes":["sh-session"],"name":"shellsession","patterns":[{"captures":{"1":{"name":"entity.other.prompt-prefix.shell-session"},"2":{"name":"punctuation.separator.prompt.shell-session"},"3":{"name":"source.shell","patterns":[{"include":"source.shell"}]}},"match":"^(?:((?:\\\\(\\\\S+\\\\)\\\\s*)?(?:sh\\\\S*?|\\\\w+\\\\S+[:@]\\\\S+(?:\\\\s+\\\\S+)?|\\\\[\\\\S+?[:@]\\\\N+?].*?))\\\\s*)?([#\$%>❯➜\\\\p{Greek}])\\\\s+(.*)\$"},{"match":"^.+\$","name":"meta.output.shell-session"}],"scopeName":"text.shell-session"}';
