// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../core/code_language.dart';
import 'typescript.dart';
import 'es_tag_css.dart';
import 'es_tag_glsl.dart';
import 'es_tag_html.dart';
import 'es_tag_sql.dart';
import 'es_tag_xml.dart';

/// TypeScript with Tags grammar (scope `source.ts.tags`).
const CodeLanguage tsTags = CodeLanguage(
  id: 'ts-tags',
  scopeName: 'source.ts.tags',
  displayName: 'TypeScript with Tags',
  json: _json,
  embeddedLanguages: _embedded,
  aliases: ['lit'],
  categories: [GrammarCategory.web],
);

List<CodeLanguage> _embedded() => [
  typescript,
  esTagCss,
  esTagGlsl,
  esTagHtml,
  esTagSql,
  esTagXml,
];

const _json =
    '{"displayName":"TypeScript with Tags","name":"ts-tags","patterns":[{"include":"source.ts"}],"scopeName":"source.ts.tags"}';
