// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../core/code_language.dart';

/// vue-directives grammar (scope `vue.directives`).
const CodeLanguage vueDirectives = CodeLanguage(
  id: 'vue-directives',
  scopeName: 'vue.directives',
  displayName: 'vue-directives',
  json: _json,
);

const _json =
    '{"fileTypes":[],"injectTo":["source.vue","text.html.markdown","text.html.derivative","text.pug"],"injectionSelector":"L:meta.tag -meta.attribute -meta.ng-binding -entity.name.tag.pug -attribute_value -source.tsx -source.js.jsx, L:meta.element -meta.attribute","name":"vue-directives","patterns":[{"include":"text.html.vue#vue-directives"}],"scopeName":"vue.directives"}';
