// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../core/code_language.dart';
import 'javascript.dart';

/// vue-sfc-style-variable-injection grammar (scope `vue.sfc.style.variable.injection`).
const CodeLanguage vueSfcStyleVariableInjection = CodeLanguage(
  id: 'vue-sfc-style-variable-injection',
  scopeName: 'vue.sfc.style.variable.injection',
  displayName: 'vue-sfc-style-variable-injection',
  json: _json,
  embeddedLanguages: _embedded,
);

List<CodeLanguage> _embedded() => [javascript];

const _json =
    '{"fileTypes":[],"injectTo":["source.vue"],"injectionSelector":"L:source.css -comment, L:source.postcss -comment, L:source.sass -comment, L:source.stylus -comment","name":"vue-sfc-style-variable-injection","patterns":[{"include":"#vue-sfc-style-variable-injection"}],"repository":{"vue-sfc-style-variable-injection":{"begin":"\\\\b(v-bind)\\\\s*\\\\(","beginCaptures":{"1":{"name":"entity.name.function"}},"end":"\\\\)","name":"vue.sfc.style.variable.injection.v-bind","patterns":[{"begin":"([\\"\'])","beginCaptures":{"1":{"name":"punctuation.definition.tag.begin.html"}},"end":"(\\\\1)","endCaptures":{"1":{"name":"punctuation.definition.tag.end.html"}},"name":"source.ts.embedded.html.vue","patterns":[{"include":"source.js"}]},{"include":"source.js"}]}},"scopeName":"vue.sfc.style.variable.injection"}';
