// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../core/code_language.dart';

/// vue-interpolations grammar (scope `vue.interpolations`).
const CodeLanguage vueInterpolations = CodeLanguage(
  id: 'vue-interpolations',
  scopeName: 'vue.interpolations',
  displayName: 'vue-interpolations',
  json: _json,
);

const _json =
    '{"fileTypes":[],"injectTo":["source.vue","text.html.markdown","text.html.derivative","text.pug"],"injectionSelector":"L:text.pug -comment -string.comment, L:text.html.derivative -comment.block, L:text.html.markdown -comment.block","name":"vue-interpolations","patterns":[{"include":"text.html.vue#vue-interpolations"}],"scopeName":"vue.interpolations"}';
