// GENERATED by tool/generate_bundled.dart. Do not edit.
//
// Typesafe, tree-shakeable access to the bundled languages.
// Referencing a member (e.g. `CodeLanguages.dart`) pulls in only
// that grammar and its embedded deps; the rest are tree-shaken away.

import 'src/core/code_language.dart';
export 'src/core/code_language.dart' show CodeLanguage, GrammarCategory;
import 'src/langs/abap.dart' as l_abap;
import 'src/langs/actionscript_3.dart' as l_actionscript_3;
import 'src/langs/ada.dart' as l_ada;
import 'src/langs/angular_html.dart' as l_angular_html;
import 'src/langs/angular_ts.dart' as l_angular_ts;
import 'src/langs/apache.dart' as l_apache;
import 'src/langs/apex.dart' as l_apex;
import 'src/langs/apl.dart' as l_apl;
import 'src/langs/applescript.dart' as l_applescript;
import 'src/langs/ara.dart' as l_ara;
import 'src/langs/asciidoc.dart' as l_asciidoc;
import 'src/langs/asm.dart' as l_asm;
import 'src/langs/astro.dart' as l_astro;
import 'src/langs/awk.dart' as l_awk;
import 'src/langs/ballerina.dart' as l_ballerina;
import 'src/langs/bat.dart' as l_bat;
import 'src/langs/beancount.dart' as l_beancount;
import 'src/langs/berry.dart' as l_berry;
import 'src/langs/bibtex.dart' as l_bibtex;
import 'src/langs/bicep.dart' as l_bicep;
import 'src/langs/bird2.dart' as l_bird2;
import 'src/langs/blade.dart' as l_blade;
import 'src/langs/bsl.dart' as l_bsl;
import 'src/langs/c.dart' as l_c;
import 'src/langs/c3.dart' as l_c3;
import 'src/langs/cadence.dart' as l_cadence;
import 'src/langs/cairo.dart' as l_cairo;
import 'src/langs/clarity.dart' as l_clarity;
import 'src/langs/clojure.dart' as l_clojure;
import 'src/langs/cmake.dart' as l_cmake;
import 'src/langs/cobol.dart' as l_cobol;
import 'src/langs/codeowners.dart' as l_codeowners;
import 'src/langs/codeql.dart' as l_codeql;
import 'src/langs/coffee.dart' as l_coffee;
import 'src/langs/common_lisp.dart' as l_common_lisp;
import 'src/langs/coq.dart' as l_coq;
import 'src/langs/cpp.dart' as l_cpp;
import 'src/langs/crystal.dart' as l_crystal;
import 'src/langs/csharp.dart' as l_csharp;
import 'src/langs/css.dart' as l_css;
import 'src/langs/csv.dart' as l_csv;
import 'src/langs/cue.dart' as l_cue;
import 'src/langs/cypher.dart' as l_cypher;
import 'src/langs/d.dart' as l_d;
import 'src/langs/dart.dart' as l_dart;
import 'src/langs/dax.dart' as l_dax;
import 'src/langs/desktop.dart' as l_desktop;
import 'src/langs/diff.dart' as l_diff;
import 'src/langs/docker.dart' as l_docker;
import 'src/langs/dotenv.dart' as l_dotenv;
import 'src/langs/dream_maker.dart' as l_dream_maker;
import 'src/langs/edge.dart' as l_edge;
import 'src/langs/elixir.dart' as l_elixir;
import 'src/langs/elm.dart' as l_elm;
import 'src/langs/emacs_lisp.dart' as l_emacs_lisp;
import 'src/langs/erb.dart' as l_erb;
import 'src/langs/erlang.dart' as l_erlang;
import 'src/langs/fennel.dart' as l_fennel;
import 'src/langs/fish.dart' as l_fish;
import 'src/langs/fluent.dart' as l_fluent;
import 'src/langs/fortran_fixed_form.dart' as l_fortran_fixed_form;
import 'src/langs/fortran_free_form.dart' as l_fortran_free_form;
import 'src/langs/fsharp.dart' as l_fsharp;
import 'src/langs/gdresource.dart' as l_gdresource;
import 'src/langs/gdscript.dart' as l_gdscript;
import 'src/langs/gdshader.dart' as l_gdshader;
import 'src/langs/genie.dart' as l_genie;
import 'src/langs/gherkin.dart' as l_gherkin;
import 'src/langs/git_commit.dart' as l_git_commit;
import 'src/langs/git_rebase.dart' as l_git_rebase;
import 'src/langs/gleam.dart' as l_gleam;
import 'src/langs/glimmer_js.dart' as l_glimmer_js;
import 'src/langs/glimmer_ts.dart' as l_glimmer_ts;
import 'src/langs/glsl.dart' as l_glsl;
import 'src/langs/gn.dart' as l_gn;
import 'src/langs/gnuplot.dart' as l_gnuplot;
import 'src/langs/go.dart' as l_go;
import 'src/langs/graphql.dart' as l_graphql;
import 'src/langs/groovy.dart' as l_groovy;
import 'src/langs/hack.dart' as l_hack;
import 'src/langs/haml.dart' as l_haml;
import 'src/langs/handlebars.dart' as l_handlebars;
import 'src/langs/haskell.dart' as l_haskell;
import 'src/langs/haxe.dart' as l_haxe;
import 'src/langs/hcl.dart' as l_hcl;
import 'src/langs/hjson.dart' as l_hjson;
import 'src/langs/hlsl.dart' as l_hlsl;
import 'src/langs/html.dart' as l_html;
import 'src/langs/html_derivative.dart' as l_html_derivative;
import 'src/langs/http.dart' as l_http;
import 'src/langs/hurl.dart' as l_hurl;
import 'src/langs/hxml.dart' as l_hxml;
import 'src/langs/hy.dart' as l_hy;
import 'src/langs/imba.dart' as l_imba;
import 'src/langs/ini.dart' as l_ini;
import 'src/langs/java.dart' as l_java;
import 'src/langs/javascript.dart' as l_javascript;
import 'src/langs/jinja.dart' as l_jinja;
import 'src/langs/jison.dart' as l_jison;
import 'src/langs/json.dart' as l_json;
import 'src/langs/json5.dart' as l_json5;
import 'src/langs/jsonc.dart' as l_jsonc;
import 'src/langs/jsonl.dart' as l_jsonl;
import 'src/langs/jsonnet.dart' as l_jsonnet;
import 'src/langs/jssm.dart' as l_jssm;
import 'src/langs/jsx.dart' as l_jsx;
import 'src/langs/julia.dart' as l_julia;
import 'src/langs/just.dart' as l_just;
import 'src/langs/kdl.dart' as l_kdl;
import 'src/langs/kotlin.dart' as l_kotlin;
import 'src/langs/kusto.dart' as l_kusto;
import 'src/langs/latex.dart' as l_latex;
import 'src/langs/lean.dart' as l_lean;
import 'src/langs/less.dart' as l_less;
import 'src/langs/liquid.dart' as l_liquid;
import 'src/langs/llvm.dart' as l_llvm;
import 'src/langs/log.dart' as l_log;
import 'src/langs/logo.dart' as l_logo;
import 'src/langs/lua.dart' as l_lua;
import 'src/langs/luau.dart' as l_luau;
import 'src/langs/make.dart' as l_make;
import 'src/langs/markdown.dart' as l_markdown;
import 'src/langs/marko.dart' as l_marko;
import 'src/langs/matlab.dart' as l_matlab;
import 'src/langs/mdc.dart' as l_mdc;
import 'src/langs/mdx.dart' as l_mdx;
import 'src/langs/mermaid.dart' as l_mermaid;
import 'src/langs/mipsasm.dart' as l_mipsasm;
import 'src/langs/mojo.dart' as l_mojo;
import 'src/langs/moonbit.dart' as l_moonbit;
import 'src/langs/move.dart' as l_move;
import 'src/langs/narrat.dart' as l_narrat;
import 'src/langs/nextflow.dart' as l_nextflow;
import 'src/langs/nextflow_groovy.dart' as l_nextflow_groovy;
import 'src/langs/nginx.dart' as l_nginx;
import 'src/langs/nim.dart' as l_nim;
import 'src/langs/nix.dart' as l_nix;
import 'src/langs/nushell.dart' as l_nushell;
import 'src/langs/objective_c.dart' as l_objective_c;
import 'src/langs/objective_cpp.dart' as l_objective_cpp;
import 'src/langs/ocaml.dart' as l_ocaml;
import 'src/langs/odin.dart' as l_odin;
import 'src/langs/openscad.dart' as l_openscad;
import 'src/langs/pascal.dart' as l_pascal;
import 'src/langs/perl.dart' as l_perl;
import 'src/langs/php.dart' as l_php;
import 'src/langs/pkl.dart' as l_pkl;
import 'src/langs/plsql.dart' as l_plsql;
import 'src/langs/po.dart' as l_po;
import 'src/langs/polar.dart' as l_polar;
import 'src/langs/postcss.dart' as l_postcss;
import 'src/langs/powerquery.dart' as l_powerquery;
import 'src/langs/powershell.dart' as l_powershell;
import 'src/langs/prisma.dart' as l_prisma;
import 'src/langs/prolog.dart' as l_prolog;
import 'src/langs/proto.dart' as l_proto;
import 'src/langs/pug.dart' as l_pug;
import 'src/langs/puppet.dart' as l_puppet;
import 'src/langs/purescript.dart' as l_purescript;
import 'src/langs/python.dart' as l_python;
import 'src/langs/qml.dart' as l_qml;
import 'src/langs/qmldir.dart' as l_qmldir;
import 'src/langs/qss.dart' as l_qss;
import 'src/langs/r.dart' as l_r;
import 'src/langs/racket.dart' as l_racket;
import 'src/langs/raku.dart' as l_raku;
import 'src/langs/razor.dart' as l_razor;
import 'src/langs/reg.dart' as l_reg;
import 'src/langs/regexp.dart' as l_regexp;
import 'src/langs/rel.dart' as l_rel;
import 'src/langs/riscv.dart' as l_riscv;
import 'src/langs/ron.dart' as l_ron;
import 'src/langs/rosmsg.dart' as l_rosmsg;
import 'src/langs/rst.dart' as l_rst;
import 'src/langs/ruby.dart' as l_ruby;
import 'src/langs/rust.dart' as l_rust;
import 'src/langs/sas.dart' as l_sas;
import 'src/langs/sass.dart' as l_sass;
import 'src/langs/scala.dart' as l_scala;
import 'src/langs/scheme.dart' as l_scheme;
import 'src/langs/scss.dart' as l_scss;
import 'src/langs/sdbl.dart' as l_sdbl;
import 'src/langs/shaderlab.dart' as l_shaderlab;
import 'src/langs/shellscript.dart' as l_shellscript;
import 'src/langs/shellsession.dart' as l_shellsession;
import 'src/langs/smalltalk.dart' as l_smalltalk;
import 'src/langs/solidity.dart' as l_solidity;
import 'src/langs/soy.dart' as l_soy;
import 'src/langs/sparql.dart' as l_sparql;
import 'src/langs/splunk.dart' as l_splunk;
import 'src/langs/sql.dart' as l_sql;
import 'src/langs/ssh_config.dart' as l_ssh_config;
import 'src/langs/stata.dart' as l_stata;
import 'src/langs/stylus.dart' as l_stylus;
import 'src/langs/surrealql.dart' as l_surrealql;
import 'src/langs/svelte.dart' as l_svelte;
import 'src/langs/swift.dart' as l_swift;
import 'src/langs/system_verilog.dart' as l_system_verilog;
import 'src/langs/systemd.dart' as l_systemd;
import 'src/langs/talonscript.dart' as l_talonscript;
import 'src/langs/tasl.dart' as l_tasl;
import 'src/langs/tcl.dart' as l_tcl;
import 'src/langs/templ.dart' as l_templ;
import 'src/langs/terraform.dart' as l_terraform;
import 'src/langs/tex.dart' as l_tex;
import 'src/langs/toml.dart' as l_toml;
import 'src/langs/ts_tags.dart' as l_ts_tags;
import 'src/langs/tsv.dart' as l_tsv;
import 'src/langs/tsx.dart' as l_tsx;
import 'src/langs/turtle.dart' as l_turtle;
import 'src/langs/twig.dart' as l_twig;
import 'src/langs/typescript.dart' as l_typescript;
import 'src/langs/typespec.dart' as l_typespec;
import 'src/langs/typst.dart' as l_typst;
import 'src/langs/v.dart' as l_v;
import 'src/langs/vala.dart' as l_vala;
import 'src/langs/vb.dart' as l_vb;
import 'src/langs/verilog.dart' as l_verilog;
import 'src/langs/vhdl.dart' as l_vhdl;
import 'src/langs/viml.dart' as l_viml;
import 'src/langs/vue.dart' as l_vue;
import 'src/langs/vue_html.dart' as l_vue_html;
import 'src/langs/vue_vine.dart' as l_vue_vine;
import 'src/langs/vyper.dart' as l_vyper;
import 'src/langs/wasm.dart' as l_wasm;
import 'src/langs/wenyan.dart' as l_wenyan;
import 'src/langs/wgsl.dart' as l_wgsl;
import 'src/langs/wikitext.dart' as l_wikitext;
import 'src/langs/wit.dart' as l_wit;
import 'src/langs/wolfram.dart' as l_wolfram;
import 'src/langs/xml.dart' as l_xml;
import 'src/langs/xsl.dart' as l_xsl;
import 'src/langs/yaml.dart' as l_yaml;
import 'src/langs/zenscript.dart' as l_zenscript;
import 'src/langs/zig.dart' as l_zig;

/// Typesafe, tree-shakeable access to every language grammar bundled with
/// the package. Referencing a member (e.g. [abap]) pulls in only that
/// grammar and its embedded dependencies; grammars you never reference are
/// tree-shaken out of the build.
abstract final class CodeLanguages {
  /// ABAP.
  static const CodeLanguage abap = l_abap.abap;

  /// ActionScript.
  static const CodeLanguage actionscript3 = l_actionscript_3.actionscript3;

  /// Ada.
  static const CodeLanguage ada = l_ada.ada;

  /// Angular HTML.
  static const CodeLanguage angularHtml = l_angular_html.angularHtml;

  /// Angular TypeScript.
  static const CodeLanguage angularTs = l_angular_ts.angularTs;

  /// Apache Conf.
  static const CodeLanguage apache = l_apache.apache;

  /// Apex.
  static const CodeLanguage apex = l_apex.apex;

  /// APL.
  static const CodeLanguage apl = l_apl.apl;

  /// AppleScript.
  static const CodeLanguage applescript = l_applescript.applescript;

  /// Ara.
  static const CodeLanguage ara = l_ara.ara;

  /// AsciiDoc.
  static const CodeLanguage asciidoc = l_asciidoc.asciidoc;

  /// Assembly.
  static const CodeLanguage asm = l_asm.asm;

  /// Astro.
  static const CodeLanguage astro = l_astro.astro;

  /// AWK.
  static const CodeLanguage awk = l_awk.awk;

  /// Ballerina.
  static const CodeLanguage ballerina = l_ballerina.ballerina;

  /// Batch File.
  static const CodeLanguage bat = l_bat.bat;

  /// Beancount.
  static const CodeLanguage beancount = l_beancount.beancount;

  /// Berry.
  static const CodeLanguage berry = l_berry.berry;

  /// BibTeX.
  static const CodeLanguage bibtex = l_bibtex.bibtex;

  /// Bicep.
  static const CodeLanguage bicep = l_bicep.bicep;

  /// BIRD2 Configuration.
  static const CodeLanguage bird2 = l_bird2.bird2;

  /// Blade.
  static const CodeLanguage blade = l_blade.blade;

  /// 1C (Enterprise).
  static const CodeLanguage bsl = l_bsl.bsl;

  /// C.
  static const CodeLanguage c = l_c.c;

  /// C3.
  static const CodeLanguage c3 = l_c3.c3;

  /// Cadence.
  static const CodeLanguage cadence = l_cadence.cadence;

  /// Cairo.
  static const CodeLanguage cairo = l_cairo.cairo;

  /// Clarity.
  static const CodeLanguage clarity = l_clarity.clarity;

  /// Clojure.
  static const CodeLanguage clojure = l_clojure.clojure;

  /// CMake.
  static const CodeLanguage cmake = l_cmake.cmake;

  /// COBOL.
  static const CodeLanguage cobol = l_cobol.cobol;

  /// CODEOWNERS.
  static const CodeLanguage codeowners = l_codeowners.codeowners;

  /// CodeQL.
  static const CodeLanguage codeql = l_codeql.codeql;

  /// CoffeeScript.
  static const CodeLanguage coffee = l_coffee.coffee;

  /// Common Lisp.
  static const CodeLanguage commonLisp = l_common_lisp.commonLisp;

  /// Coq.
  static const CodeLanguage coq = l_coq.coq;

  /// C++.
  static const CodeLanguage cpp = l_cpp.cpp;

  /// Crystal.
  static const CodeLanguage crystal = l_crystal.crystal;

  /// C#.
  static const CodeLanguage csharp = l_csharp.csharp;

  /// CSS.
  static const CodeLanguage css = l_css.css;

  /// CSV.
  static const CodeLanguage csv = l_csv.csv;

  /// CUE.
  static const CodeLanguage cue = l_cue.cue;

  /// Cypher.
  static const CodeLanguage cypher = l_cypher.cypher;

  /// D.
  static const CodeLanguage d = l_d.d;

  /// Dart.
  static const CodeLanguage dart = l_dart.dart;

  /// DAX.
  static const CodeLanguage dax = l_dax.dax;

  /// Desktop.
  static const CodeLanguage desktop = l_desktop.desktop;

  /// Diff.
  static const CodeLanguage diff = l_diff.diff;

  /// Dockerfile.
  static const CodeLanguage docker = l_docker.docker;

  /// dotEnv.
  static const CodeLanguage dotenv = l_dotenv.dotenv;

  /// Dream Maker.
  static const CodeLanguage dreamMaker = l_dream_maker.dreamMaker;

  /// Edge.
  static const CodeLanguage edge = l_edge.edge;

  /// Elixir.
  static const CodeLanguage elixir = l_elixir.elixir;

  /// Elm.
  static const CodeLanguage elm = l_elm.elm;

  /// Emacs Lisp.
  static const CodeLanguage emacsLisp = l_emacs_lisp.emacsLisp;

  /// ERB.
  static const CodeLanguage erb = l_erb.erb;

  /// Erlang.
  static const CodeLanguage erlang = l_erlang.erlang;

  /// Fennel.
  static const CodeLanguage fennel = l_fennel.fennel;

  /// Fish.
  static const CodeLanguage fish = l_fish.fish;

  /// Fluent.
  static const CodeLanguage fluent = l_fluent.fluent;

  /// Fortran (Fixed Form).
  static const CodeLanguage fortranFixedForm =
      l_fortran_fixed_form.fortranFixedForm;

  /// Fortran (Free Form).
  static const CodeLanguage fortranFreeForm =
      l_fortran_free_form.fortranFreeForm;

  /// F#.
  static const CodeLanguage fsharp = l_fsharp.fsharp;

  /// GDResource.
  static const CodeLanguage gdresource = l_gdresource.gdresource;

  /// GDScript.
  static const CodeLanguage gdscript = l_gdscript.gdscript;

  /// GDShader.
  static const CodeLanguage gdshader = l_gdshader.gdshader;

  /// Genie.
  static const CodeLanguage genie = l_genie.genie;

  /// Gherkin.
  static const CodeLanguage gherkin = l_gherkin.gherkin;

  /// Git Commit Message.
  static const CodeLanguage gitCommit = l_git_commit.gitCommit;

  /// Git Rebase Message.
  static const CodeLanguage gitRebase = l_git_rebase.gitRebase;

  /// Gleam.
  static const CodeLanguage gleam = l_gleam.gleam;

  /// Glimmer JS.
  static const CodeLanguage glimmerJs = l_glimmer_js.glimmerJs;

  /// Glimmer TS.
  static const CodeLanguage glimmerTs = l_glimmer_ts.glimmerTs;

  /// GLSL.
  static const CodeLanguage glsl = l_glsl.glsl;

  /// GN.
  static const CodeLanguage gn = l_gn.gn;

  /// Gnuplot.
  static const CodeLanguage gnuplot = l_gnuplot.gnuplot;

  /// Go.
  static const CodeLanguage go = l_go.go;

  /// GraphQL.
  static const CodeLanguage graphql = l_graphql.graphql;

  /// Groovy.
  static const CodeLanguage groovy = l_groovy.groovy;

  /// Hack.
  static const CodeLanguage hack = l_hack.hack;

  /// Ruby Haml.
  static const CodeLanguage haml = l_haml.haml;

  /// Handlebars.
  static const CodeLanguage handlebars = l_handlebars.handlebars;

  /// Haskell.
  static const CodeLanguage haskell = l_haskell.haskell;

  /// Haxe.
  static const CodeLanguage haxe = l_haxe.haxe;

  /// HashiCorp HCL.
  static const CodeLanguage hcl = l_hcl.hcl;

  /// Hjson.
  static const CodeLanguage hjson = l_hjson.hjson;

  /// HLSL.
  static const CodeLanguage hlsl = l_hlsl.hlsl;

  /// HTML.
  static const CodeLanguage html = l_html.html;

  /// HTML (Derivative).
  static const CodeLanguage htmlDerivative = l_html_derivative.htmlDerivative;

  /// HTTP.
  static const CodeLanguage http = l_http.http;

  /// Hurl.
  static const CodeLanguage hurl = l_hurl.hurl;

  /// HXML.
  static const CodeLanguage hxml = l_hxml.hxml;

  /// Hy.
  static const CodeLanguage hy = l_hy.hy;

  /// Imba.
  static const CodeLanguage imba = l_imba.imba;

  /// INI.
  static const CodeLanguage ini = l_ini.ini;

  /// Java.
  static const CodeLanguage java = l_java.java;

  /// JavaScript.
  static const CodeLanguage javascript = l_javascript.javascript;

  /// Jinja.
  static const CodeLanguage jinja = l_jinja.jinja;

  /// Jison.
  static const CodeLanguage jison = l_jison.jison;

  /// JSON.
  static const CodeLanguage json = l_json.json;

  /// JSON5.
  static const CodeLanguage json5 = l_json5.json5;

  /// JSON with Comments.
  static const CodeLanguage jsonc = l_jsonc.jsonc;

  /// JSON Lines.
  static const CodeLanguage jsonl = l_jsonl.jsonl;

  /// Jsonnet.
  static const CodeLanguage jsonnet = l_jsonnet.jsonnet;

  /// JSSM.
  static const CodeLanguage jssm = l_jssm.jssm;

  /// JSX.
  static const CodeLanguage jsx = l_jsx.jsx;

  /// Julia.
  static const CodeLanguage julia = l_julia.julia;

  /// Just.
  static const CodeLanguage just = l_just.just;

  /// KDL.
  static const CodeLanguage kdl = l_kdl.kdl;

  /// Kotlin.
  static const CodeLanguage kotlin = l_kotlin.kotlin;

  /// Kusto.
  static const CodeLanguage kusto = l_kusto.kusto;

  /// LaTeX.
  static const CodeLanguage latex = l_latex.latex;

  /// Lean 4.
  static const CodeLanguage lean = l_lean.lean;

  /// Less.
  static const CodeLanguage less = l_less.less;

  /// Liquid.
  static const CodeLanguage liquid = l_liquid.liquid;

  /// LLVM IR.
  static const CodeLanguage llvm = l_llvm.llvm;

  /// Log file.
  static const CodeLanguage log = l_log.log;

  /// Logo.
  static const CodeLanguage logo = l_logo.logo;

  /// Lua.
  static const CodeLanguage lua = l_lua.lua;

  /// Luau.
  static const CodeLanguage luau = l_luau.luau;

  /// Makefile.
  static const CodeLanguage make = l_make.make;

  /// Markdown.
  static const CodeLanguage markdown = l_markdown.markdown;

  /// Marko.
  static const CodeLanguage marko = l_marko.marko;

  /// MATLAB.
  static const CodeLanguage matlab = l_matlab.matlab;

  /// MDC.
  static const CodeLanguage mdc = l_mdc.mdc;

  /// MDX.
  static const CodeLanguage mdx = l_mdx.mdx;

  /// Mermaid.
  static const CodeLanguage mermaid = l_mermaid.mermaid;

  /// MIPS Assembly.
  static const CodeLanguage mipsasm = l_mipsasm.mipsasm;

  /// Mojo.
  static const CodeLanguage mojo = l_mojo.mojo;

  /// MoonBit.
  static const CodeLanguage moonbit = l_moonbit.moonbit;

  /// Move.
  static const CodeLanguage move = l_move.move;

  /// Narrat Language.
  static const CodeLanguage narrat = l_narrat.narrat;

  /// Nextflow.
  static const CodeLanguage nextflow = l_nextflow.nextflow;

  /// Nextflow Groovy.
  static const CodeLanguage nextflowGroovy = l_nextflow_groovy.nextflowGroovy;

  /// Nginx.
  static const CodeLanguage nginx = l_nginx.nginx;

  /// Nim.
  static const CodeLanguage nim = l_nim.nim;

  /// Nix.
  static const CodeLanguage nix = l_nix.nix;

  /// nushell.
  static const CodeLanguage nushell = l_nushell.nushell;

  /// Objective-C.
  static const CodeLanguage objectiveC = l_objective_c.objectiveC;

  /// Objective-C++.
  static const CodeLanguage objectiveCpp = l_objective_cpp.objectiveCpp;

  /// OCaml.
  static const CodeLanguage ocaml = l_ocaml.ocaml;

  /// Odin.
  static const CodeLanguage odin = l_odin.odin;

  /// OpenSCAD.
  static const CodeLanguage openscad = l_openscad.openscad;

  /// Pascal.
  static const CodeLanguage pascal = l_pascal.pascal;

  /// Perl.
  static const CodeLanguage perl = l_perl.perl;

  /// PHP.
  static const CodeLanguage php = l_php.php;

  /// Pkl.
  static const CodeLanguage pkl = l_pkl.pkl;

  /// PL/SQL.
  static const CodeLanguage plsql = l_plsql.plsql;

  /// Gettext PO.
  static const CodeLanguage po = l_po.po;

  /// Polar.
  static const CodeLanguage polar = l_polar.polar;

  /// PostCSS.
  static const CodeLanguage postcss = l_postcss.postcss;

  /// PowerQuery.
  static const CodeLanguage powerquery = l_powerquery.powerquery;

  /// PowerShell.
  static const CodeLanguage powershell = l_powershell.powershell;

  /// Prisma.
  static const CodeLanguage prisma = l_prisma.prisma;

  /// Prolog.
  static const CodeLanguage prolog = l_prolog.prolog;

  /// Protocol Buffer 3.
  static const CodeLanguage proto = l_proto.proto;

  /// Pug.
  static const CodeLanguage pug = l_pug.pug;

  /// Puppet.
  static const CodeLanguage puppet = l_puppet.puppet;

  /// PureScript.
  static const CodeLanguage purescript = l_purescript.purescript;

  /// Python.
  static const CodeLanguage python = l_python.python;

  /// QML.
  static const CodeLanguage qml = l_qml.qml;

  /// QML Directory.
  static const CodeLanguage qmldir = l_qmldir.qmldir;

  /// Qt Style Sheets.
  static const CodeLanguage qss = l_qss.qss;

  /// R.
  static const CodeLanguage r = l_r.r;

  /// Racket.
  static const CodeLanguage racket = l_racket.racket;

  /// Raku.
  static const CodeLanguage raku = l_raku.raku;

  /// ASP.NET Razor.
  static const CodeLanguage razor = l_razor.razor;

  /// Windows Registry Script.
  static const CodeLanguage reg = l_reg.reg;

  /// RegExp.
  static const CodeLanguage regexp = l_regexp.regexp;

  /// Rel.
  static const CodeLanguage rel = l_rel.rel;

  /// RISC-V.
  static const CodeLanguage riscv = l_riscv.riscv;

  /// RON.
  static const CodeLanguage ron = l_ron.ron;

  /// ROS Interface.
  static const CodeLanguage rosmsg = l_rosmsg.rosmsg;

  /// reStructuredText.
  static const CodeLanguage rst = l_rst.rst;

  /// Ruby.
  static const CodeLanguage ruby = l_ruby.ruby;

  /// Rust.
  static const CodeLanguage rust = l_rust.rust;

  /// SAS.
  static const CodeLanguage sas = l_sas.sas;

  /// Sass.
  static const CodeLanguage sass = l_sass.sass;

  /// Scala.
  static const CodeLanguage scala = l_scala.scala;

  /// Scheme.
  static const CodeLanguage scheme = l_scheme.scheme;

  /// SCSS.
  static const CodeLanguage scss = l_scss.scss;

  /// 1C (Query).
  static const CodeLanguage sdbl = l_sdbl.sdbl;

  /// ShaderLab.
  static const CodeLanguage shaderlab = l_shaderlab.shaderlab;

  /// Shell.
  static const CodeLanguage shellscript = l_shellscript.shellscript;

  /// Shell Session.
  static const CodeLanguage shellsession = l_shellsession.shellsession;

  /// Smalltalk.
  static const CodeLanguage smalltalk = l_smalltalk.smalltalk;

  /// Solidity.
  static const CodeLanguage solidity = l_solidity.solidity;

  /// Closure Templates.
  static const CodeLanguage soy = l_soy.soy;

  /// SPARQL.
  static const CodeLanguage sparql = l_sparql.sparql;

  /// Splunk Query Language.
  static const CodeLanguage splunk = l_splunk.splunk;

  /// SQL.
  static const CodeLanguage sql = l_sql.sql;

  /// SSH Config.
  static const CodeLanguage sshConfig = l_ssh_config.sshConfig;

  /// Stata.
  static const CodeLanguage stata = l_stata.stata;

  /// Stylus.
  static const CodeLanguage stylus = l_stylus.stylus;

  /// SurrealQL.
  static const CodeLanguage surrealql = l_surrealql.surrealql;

  /// Svelte.
  static const CodeLanguage svelte = l_svelte.svelte;

  /// Swift.
  static const CodeLanguage swift = l_swift.swift;

  /// SystemVerilog.
  static const CodeLanguage systemVerilog = l_system_verilog.systemVerilog;

  /// Systemd Units.
  static const CodeLanguage systemd = l_systemd.systemd;

  /// TalonScript.
  static const CodeLanguage talonscript = l_talonscript.talonscript;

  /// Tasl.
  static const CodeLanguage tasl = l_tasl.tasl;

  /// Tcl.
  static const CodeLanguage tcl = l_tcl.tcl;

  /// Templ.
  static const CodeLanguage templ = l_templ.templ;

  /// Terraform.
  static const CodeLanguage terraform = l_terraform.terraform;

  /// TeX.
  static const CodeLanguage tex = l_tex.tex;

  /// TOML.
  static const CodeLanguage toml = l_toml.toml;

  /// TypeScript with Tags.
  static const CodeLanguage tsTags = l_ts_tags.tsTags;

  /// TSV.
  static const CodeLanguage tsv = l_tsv.tsv;

  /// TSX.
  static const CodeLanguage tsx = l_tsx.tsx;

  /// Turtle.
  static const CodeLanguage turtle = l_turtle.turtle;

  /// Twig.
  static const CodeLanguage twig = l_twig.twig;

  /// TypeScript.
  static const CodeLanguage typescript = l_typescript.typescript;

  /// TypeSpec.
  static const CodeLanguage typespec = l_typespec.typespec;

  /// Typst.
  static const CodeLanguage typst = l_typst.typst;

  /// V.
  static const CodeLanguage v = l_v.v;

  /// Vala.
  static const CodeLanguage vala = l_vala.vala;

  /// Visual Basic.
  static const CodeLanguage vb = l_vb.vb;

  /// Verilog.
  static const CodeLanguage verilog = l_verilog.verilog;

  /// VHDL.
  static const CodeLanguage vhdl = l_vhdl.vhdl;

  /// Vim Script.
  static const CodeLanguage viml = l_viml.viml;

  /// Vue.
  static const CodeLanguage vue = l_vue.vue;

  /// Vue HTML.
  static const CodeLanguage vueHtml = l_vue_html.vueHtml;

  /// Vue Vine.
  static const CodeLanguage vueVine = l_vue_vine.vueVine;

  /// Vyper.
  static const CodeLanguage vyper = l_vyper.vyper;

  /// WebAssembly.
  static const CodeLanguage wasm = l_wasm.wasm;

  /// Wenyan.
  static const CodeLanguage wenyan = l_wenyan.wenyan;

  /// WGSL.
  static const CodeLanguage wgsl = l_wgsl.wgsl;

  /// Wikitext.
  static const CodeLanguage wikitext = l_wikitext.wikitext;

  /// WebAssembly Interface Types.
  static const CodeLanguage wit = l_wit.wit;

  /// Wolfram.
  static const CodeLanguage wolfram = l_wolfram.wolfram;

  /// XML.
  static const CodeLanguage xml = l_xml.xml;

  /// XSL.
  static const CodeLanguage xsl = l_xsl.xsl;

  /// YAML.
  static const CodeLanguage yaml = l_yaml.yaml;

  /// ZenScript.
  static const CodeLanguage zenscript = l_zenscript.zenscript;

  /// Zig.
  static const CodeLanguage zig = l_zig.zig;

  // CAUTION: referencing `all` pulls EVERY grammar into your build
  // (defeats tree-shaking). Prefer individual members; use this only
  // when you truly need every language.
  /// Every bundled language grammar. Referencing this pulls all of them into
  /// your build, defeating tree-shaking; prefer individual members (e.g.
  /// [abap]) unless you truly need every language.
  static const List<CodeLanguage> all = [
    abap,
    actionscript3,
    ada,
    angularHtml,
    angularTs,
    apache,
    apex,
    apl,
    applescript,
    ara,
    asciidoc,
    asm,
    astro,
    awk,
    ballerina,
    bat,
    beancount,
    berry,
    bibtex,
    bicep,
    bird2,
    blade,
    bsl,
    c,
    c3,
    cadence,
    cairo,
    clarity,
    clojure,
    cmake,
    cobol,
    codeowners,
    codeql,
    coffee,
    commonLisp,
    coq,
    cpp,
    crystal,
    csharp,
    css,
    csv,
    cue,
    cypher,
    d,
    dart,
    dax,
    desktop,
    diff,
    docker,
    dotenv,
    dreamMaker,
    edge,
    elixir,
    elm,
    emacsLisp,
    erb,
    erlang,
    fennel,
    fish,
    fluent,
    fortranFixedForm,
    fortranFreeForm,
    fsharp,
    gdresource,
    gdscript,
    gdshader,
    genie,
    gherkin,
    gitCommit,
    gitRebase,
    gleam,
    glimmerJs,
    glimmerTs,
    glsl,
    gn,
    gnuplot,
    go,
    graphql,
    groovy,
    hack,
    haml,
    handlebars,
    haskell,
    haxe,
    hcl,
    hjson,
    hlsl,
    html,
    htmlDerivative,
    http,
    hurl,
    hxml,
    hy,
    imba,
    ini,
    java,
    javascript,
    jinja,
    jison,
    json,
    json5,
    jsonc,
    jsonl,
    jsonnet,
    jssm,
    jsx,
    julia,
    just,
    kdl,
    kotlin,
    kusto,
    latex,
    lean,
    less,
    liquid,
    llvm,
    log,
    logo,
    lua,
    luau,
    make,
    markdown,
    marko,
    matlab,
    mdc,
    mdx,
    mermaid,
    mipsasm,
    mojo,
    moonbit,
    move,
    narrat,
    nextflow,
    nextflowGroovy,
    nginx,
    nim,
    nix,
    nushell,
    objectiveC,
    objectiveCpp,
    ocaml,
    odin,
    openscad,
    pascal,
    perl,
    php,
    pkl,
    plsql,
    po,
    polar,
    postcss,
    powerquery,
    powershell,
    prisma,
    prolog,
    proto,
    pug,
    puppet,
    purescript,
    python,
    qml,
    qmldir,
    qss,
    r,
    racket,
    raku,
    razor,
    reg,
    regexp,
    rel,
    riscv,
    ron,
    rosmsg,
    rst,
    ruby,
    rust,
    sas,
    sass,
    scala,
    scheme,
    scss,
    sdbl,
    shaderlab,
    shellscript,
    shellsession,
    smalltalk,
    solidity,
    soy,
    sparql,
    splunk,
    sql,
    sshConfig,
    stata,
    stylus,
    surrealql,
    svelte,
    swift,
    systemVerilog,
    systemd,
    talonscript,
    tasl,
    tcl,
    templ,
    terraform,
    tex,
    toml,
    tsTags,
    tsv,
    tsx,
    turtle,
    twig,
    typescript,
    typespec,
    typst,
    v,
    vala,
    vb,
    verilog,
    vhdl,
    viml,
    vue,
    vueHtml,
    vueVine,
    vyper,
    wasm,
    wenyan,
    wgsl,
    wikitext,
    wit,
    wolfram,
    xml,
    xsl,
    yaml,
    zenscript,
    zig,
  ];
}
