// GENERATED by tool/generate_bundled.dart. Do not edit.
//
// Pierre themes: an opt-in set of 10 custom themes by Pierre, MIT ©
// The Pierre Computer Company (https://pierre.co). Sourced from
// https://github.com/pierrecomputer/pierre/tree/main/packages/theme
// (npm: @pierre/theme). Separate from `ShikiThemes` and not counted
// among the bundled Shiki themes.
//
// Typesafe and tree-shakeable: referencing a member (e.g.
// `PierreThemes.pierreDark`) pulls in only that theme.

import 'src/core/shiki_theme.dart';
export 'src/core/shiki_theme.dart' show ShikiTheme;
import 'src/pierre_themes/pierre_dark.dart' as p_pierre_dark;
import 'src/pierre_themes/pierre_dark_protanopia_deuteranopia.dart'
    as p_pierre_dark_protanopia_deuteranopia;
import 'src/pierre_themes/pierre_dark_soft.dart' as p_pierre_dark_soft;
import 'src/pierre_themes/pierre_dark_tritanopia.dart'
    as p_pierre_dark_tritanopia;
import 'src/pierre_themes/pierre_dark_vibrant.dart' as p_pierre_dark_vibrant;
import 'src/pierre_themes/pierre_light.dart' as p_pierre_light;
import 'src/pierre_themes/pierre_light_protanopia_deuteranopia.dart'
    as p_pierre_light_protanopia_deuteranopia;
import 'src/pierre_themes/pierre_light_soft.dart' as p_pierre_light_soft;
import 'src/pierre_themes/pierre_light_tritanopia.dart'
    as p_pierre_light_tritanopia;
import 'src/pierre_themes/pierre_light_vibrant.dart' as p_pierre_light_vibrant;

abstract final class PierreThemes {
  /// Pierre Dark (dark).
  static const ShikiTheme pierreDark = p_pierre_dark.pierreDark;

  /// Pierre Dark Protanopia & Deuteranopia (dark).
  static const ShikiTheme pierreDarkProtanopiaDeuteranopia =
      p_pierre_dark_protanopia_deuteranopia.pierreDarkProtanopiaDeuteranopia;

  /// Pierre Dark Soft (dark).
  static const ShikiTheme pierreDarkSoft = p_pierre_dark_soft.pierreDarkSoft;

  /// Pierre Dark Tritanopia (dark).
  static const ShikiTheme pierreDarkTritanopia =
      p_pierre_dark_tritanopia.pierreDarkTritanopia;

  /// Pierre Dark Vibrant (dark).
  static const ShikiTheme pierreDarkVibrant =
      p_pierre_dark_vibrant.pierreDarkVibrant;

  /// Pierre Light (light).
  static const ShikiTheme pierreLight = p_pierre_light.pierreLight;

  /// Pierre Light Protanopia & Deuteranopia (light).
  static const ShikiTheme pierreLightProtanopiaDeuteranopia =
      p_pierre_light_protanopia_deuteranopia.pierreLightProtanopiaDeuteranopia;

  /// Pierre Light Soft (light).
  static const ShikiTheme pierreLightSoft = p_pierre_light_soft.pierreLightSoft;

  /// Pierre Light Tritanopia (light).
  static const ShikiTheme pierreLightTritanopia =
      p_pierre_light_tritanopia.pierreLightTritanopia;

  /// Pierre Light Vibrant (light).
  static const ShikiTheme pierreLightVibrant =
      p_pierre_light_vibrant.pierreLightVibrant;

  // CAUTION: referencing `all` pulls in all 10 Pierre themes.
  static const List<ShikiTheme> all = [
    pierreDark,
    pierreDarkProtanopiaDeuteranopia,
    pierreDarkSoft,
    pierreDarkTritanopia,
    pierreDarkVibrant,
    pierreLight,
    pierreLightProtanopiaDeuteranopia,
    pierreLightSoft,
    pierreLightTritanopia,
    pierreLightVibrant,
  ];
}
