// GENERATED by tool/generate_bundled.dart. Do not edit.
//
// Typesafe, tree-shakeable access to the bundled themes.
// Referencing a member (e.g. `ShikiThemes.githubDark`) pulls in
// only that theme; the rest are tree-shaken away.

import 'src/core/shiki_theme.dart';
export 'src/core/shiki_theme.dart' show ShikiTheme;
import 'src/themes/andromeeda.dart' as t_andromeeda;
import 'src/themes/aurora_x.dart' as t_aurora_x;
import 'src/themes/ayu_dark.dart' as t_ayu_dark;
import 'src/themes/ayu_light.dart' as t_ayu_light;
import 'src/themes/ayu_mirage.dart' as t_ayu_mirage;
import 'src/themes/catppuccin_frappe.dart' as t_catppuccin_frappe;
import 'src/themes/catppuccin_latte.dart' as t_catppuccin_latte;
import 'src/themes/catppuccin_macchiato.dart' as t_catppuccin_macchiato;
import 'src/themes/catppuccin_mocha.dart' as t_catppuccin_mocha;
import 'src/themes/dark_plus.dart' as t_dark_plus;
import 'src/themes/dracula.dart' as t_dracula;
import 'src/themes/dracula_soft.dart' as t_dracula_soft;
import 'src/themes/everforest_dark.dart' as t_everforest_dark;
import 'src/themes/everforest_light.dart' as t_everforest_light;
import 'src/themes/github_dark.dart' as t_github_dark;
import 'src/themes/github_dark_default.dart' as t_github_dark_default;
import 'src/themes/github_dark_dimmed.dart' as t_github_dark_dimmed;
import 'src/themes/github_dark_high_contrast.dart'
    as t_github_dark_high_contrast;
import 'src/themes/github_light.dart' as t_github_light;
import 'src/themes/github_light_default.dart' as t_github_light_default;
import 'src/themes/github_light_high_contrast.dart'
    as t_github_light_high_contrast;
import 'src/themes/gruvbox_dark_hard.dart' as t_gruvbox_dark_hard;
import 'src/themes/gruvbox_dark_medium.dart' as t_gruvbox_dark_medium;
import 'src/themes/gruvbox_dark_soft.dart' as t_gruvbox_dark_soft;
import 'src/themes/gruvbox_light_hard.dart' as t_gruvbox_light_hard;
import 'src/themes/gruvbox_light_medium.dart' as t_gruvbox_light_medium;
import 'src/themes/gruvbox_light_soft.dart' as t_gruvbox_light_soft;
import 'src/themes/horizon.dart' as t_horizon;
import 'src/themes/horizon_bright.dart' as t_horizon_bright;
import 'src/themes/houston.dart' as t_houston;
import 'src/themes/kanagawa_dragon.dart' as t_kanagawa_dragon;
import 'src/themes/kanagawa_lotus.dart' as t_kanagawa_lotus;
import 'src/themes/kanagawa_wave.dart' as t_kanagawa_wave;
import 'src/themes/laserwave.dart' as t_laserwave;
import 'src/themes/light_plus.dart' as t_light_plus;
import 'src/themes/material_theme.dart' as t_material_theme;
import 'src/themes/material_theme_darker.dart' as t_material_theme_darker;
import 'src/themes/material_theme_lighter.dart' as t_material_theme_lighter;
import 'src/themes/material_theme_ocean.dart' as t_material_theme_ocean;
import 'src/themes/material_theme_palenight.dart' as t_material_theme_palenight;
import 'src/themes/min_dark.dart' as t_min_dark;
import 'src/themes/min_light.dart' as t_min_light;
import 'src/themes/monokai.dart' as t_monokai;
import 'src/themes/night_owl.dart' as t_night_owl;
import 'src/themes/night_owl_light.dart' as t_night_owl_light;
import 'src/themes/nord.dart' as t_nord;
import 'src/themes/one_dark_pro.dart' as t_one_dark_pro;
import 'src/themes/one_light.dart' as t_one_light;
import 'src/themes/plastic.dart' as t_plastic;
import 'src/themes/poimandres.dart' as t_poimandres;
import 'src/themes/red.dart' as t_red;
import 'src/themes/rose_pine.dart' as t_rose_pine;
import 'src/themes/rose_pine_dawn.dart' as t_rose_pine_dawn;
import 'src/themes/rose_pine_moon.dart' as t_rose_pine_moon;
import 'src/themes/slack_dark.dart' as t_slack_dark;
import 'src/themes/slack_ochin.dart' as t_slack_ochin;
import 'src/themes/snazzy_light.dart' as t_snazzy_light;
import 'src/themes/solarized_dark.dart' as t_solarized_dark;
import 'src/themes/solarized_light.dart' as t_solarized_light;
import 'src/themes/synthwave_84.dart' as t_synthwave_84;
import 'src/themes/tokyo_night.dart' as t_tokyo_night;
import 'src/themes/vesper.dart' as t_vesper;
import 'src/themes/vitesse_black.dart' as t_vitesse_black;
import 'src/themes/vitesse_dark.dart' as t_vitesse_dark;
import 'src/themes/vitesse_light.dart' as t_vitesse_light;

/// Typesafe, tree-shakeable access to every theme bundled with the package.
/// Referencing a member (e.g. [andromeeda]) pulls in only that theme; themes
/// you never reference are tree-shaken out of the build.
abstract final class ShikiThemes {
  /// Andromeeda (dark).
  static const ShikiTheme andromeeda = t_andromeeda.andromeeda;

  /// Aurora X (dark).
  static const ShikiTheme auroraX = t_aurora_x.auroraX;

  /// Ayu Dark (dark).
  static const ShikiTheme ayuDark = t_ayu_dark.ayuDark;

  /// Ayu Light (light).
  static const ShikiTheme ayuLight = t_ayu_light.ayuLight;

  /// Ayu Mirage (dark).
  static const ShikiTheme ayuMirage = t_ayu_mirage.ayuMirage;

  /// Catppuccin Frappé (dark).
  static const ShikiTheme catppuccinFrappe =
      t_catppuccin_frappe.catppuccinFrappe;

  /// Catppuccin Latte (light).
  static const ShikiTheme catppuccinLatte = t_catppuccin_latte.catppuccinLatte;

  /// Catppuccin Macchiato (dark).
  static const ShikiTheme catppuccinMacchiato =
      t_catppuccin_macchiato.catppuccinMacchiato;

  /// Catppuccin Mocha (dark).
  static const ShikiTheme catppuccinMocha = t_catppuccin_mocha.catppuccinMocha;

  /// Dark Plus (dark).
  static const ShikiTheme darkPlus = t_dark_plus.darkPlus;

  /// Dracula Theme (dark).
  static const ShikiTheme dracula = t_dracula.dracula;

  /// Dracula Theme Soft (dark).
  static const ShikiTheme draculaSoft = t_dracula_soft.draculaSoft;

  /// Everforest Dark (dark).
  static const ShikiTheme everforestDark = t_everforest_dark.everforestDark;

  /// Everforest Light (light).
  static const ShikiTheme everforestLight = t_everforest_light.everforestLight;

  /// GitHub Dark (dark).
  static const ShikiTheme githubDark = t_github_dark.githubDark;

  /// GitHub Dark Default (dark).
  static const ShikiTheme githubDarkDefault =
      t_github_dark_default.githubDarkDefault;

  /// GitHub Dark Dimmed (dark).
  static const ShikiTheme githubDarkDimmed =
      t_github_dark_dimmed.githubDarkDimmed;

  /// GitHub Dark High Contrast (dark).
  static const ShikiTheme githubDarkHighContrast =
      t_github_dark_high_contrast.githubDarkHighContrast;

  /// GitHub Light (light).
  static const ShikiTheme githubLight = t_github_light.githubLight;

  /// GitHub Light Default (light).
  static const ShikiTheme githubLightDefault =
      t_github_light_default.githubLightDefault;

  /// GitHub Light High Contrast (light).
  static const ShikiTheme githubLightHighContrast =
      t_github_light_high_contrast.githubLightHighContrast;

  /// Gruvbox Dark Hard (dark).
  static const ShikiTheme gruvboxDarkHard = t_gruvbox_dark_hard.gruvboxDarkHard;

  /// Gruvbox Dark Medium (dark).
  static const ShikiTheme gruvboxDarkMedium =
      t_gruvbox_dark_medium.gruvboxDarkMedium;

  /// Gruvbox Dark Soft (dark).
  static const ShikiTheme gruvboxDarkSoft = t_gruvbox_dark_soft.gruvboxDarkSoft;

  /// Gruvbox Light Hard (light).
  static const ShikiTheme gruvboxLightHard =
      t_gruvbox_light_hard.gruvboxLightHard;

  /// Gruvbox Light Medium (light).
  static const ShikiTheme gruvboxLightMedium =
      t_gruvbox_light_medium.gruvboxLightMedium;

  /// Gruvbox Light Soft (light).
  static const ShikiTheme gruvboxLightSoft =
      t_gruvbox_light_soft.gruvboxLightSoft;

  /// Horizon (dark).
  static const ShikiTheme horizon = t_horizon.horizon;

  /// Horizon Bright (light).
  static const ShikiTheme horizonBright = t_horizon_bright.horizonBright;

  /// Houston (dark).
  static const ShikiTheme houston = t_houston.houston;

  /// Kanagawa Dragon (dark).
  static const ShikiTheme kanagawaDragon = t_kanagawa_dragon.kanagawaDragon;

  /// Kanagawa Lotus (light).
  static const ShikiTheme kanagawaLotus = t_kanagawa_lotus.kanagawaLotus;

  /// Kanagawa Wave (dark).
  static const ShikiTheme kanagawaWave = t_kanagawa_wave.kanagawaWave;

  /// LaserWave (dark).
  static const ShikiTheme laserwave = t_laserwave.laserwave;

  /// Light Plus (light).
  static const ShikiTheme lightPlus = t_light_plus.lightPlus;

  /// Material Theme (dark).
  static const ShikiTheme materialTheme = t_material_theme.materialTheme;

  /// Material Theme Darker (dark).
  static const ShikiTheme materialThemeDarker =
      t_material_theme_darker.materialThemeDarker;

  /// Material Theme Lighter (light).
  static const ShikiTheme materialThemeLighter =
      t_material_theme_lighter.materialThemeLighter;

  /// Material Theme Ocean (dark).
  static const ShikiTheme materialThemeOcean =
      t_material_theme_ocean.materialThemeOcean;

  /// Material Theme Palenight (dark).
  static const ShikiTheme materialThemePalenight =
      t_material_theme_palenight.materialThemePalenight;

  /// Min Dark (dark).
  static const ShikiTheme minDark = t_min_dark.minDark;

  /// Min Light (light).
  static const ShikiTheme minLight = t_min_light.minLight;

  /// Monokai (dark).
  static const ShikiTheme monokai = t_monokai.monokai;

  /// Night Owl (dark).
  static const ShikiTheme nightOwl = t_night_owl.nightOwl;

  /// Night Owl Light (light).
  static const ShikiTheme nightOwlLight = t_night_owl_light.nightOwlLight;

  /// Nord (dark).
  static const ShikiTheme nord = t_nord.nord;

  /// One Dark Pro (dark).
  static const ShikiTheme oneDarkPro = t_one_dark_pro.oneDarkPro;

  /// One Light (light).
  static const ShikiTheme oneLight = t_one_light.oneLight;

  /// Plastic (dark).
  static const ShikiTheme plastic = t_plastic.plastic;

  /// Poimandres (dark).
  static const ShikiTheme poimandres = t_poimandres.poimandres;

  /// Red (dark).
  static const ShikiTheme red = t_red.red;

  /// Rosé Pine (dark).
  static const ShikiTheme rosePine = t_rose_pine.rosePine;

  /// Rosé Pine Dawn (light).
  static const ShikiTheme rosePineDawn = t_rose_pine_dawn.rosePineDawn;

  /// Rosé Pine Moon (dark).
  static const ShikiTheme rosePineMoon = t_rose_pine_moon.rosePineMoon;

  /// Slack Dark (dark).
  static const ShikiTheme slackDark = t_slack_dark.slackDark;

  /// Slack Ochin (light).
  static const ShikiTheme slackOchin = t_slack_ochin.slackOchin;

  /// Snazzy Light (light).
  static const ShikiTheme snazzyLight = t_snazzy_light.snazzyLight;

  /// Solarized Dark (dark).
  static const ShikiTheme solarizedDark = t_solarized_dark.solarizedDark;

  /// Solarized Light (light).
  static const ShikiTheme solarizedLight = t_solarized_light.solarizedLight;

  /// Synthwave '84 (dark).
  static const ShikiTheme synthwave84 = t_synthwave_84.synthwave84;

  /// Tokyo Night (dark).
  static const ShikiTheme tokyoNight = t_tokyo_night.tokyoNight;

  /// Vesper (dark).
  static const ShikiTheme vesper = t_vesper.vesper;

  /// Vitesse Black (dark).
  static const ShikiTheme vitesseBlack = t_vitesse_black.vitesseBlack;

  /// Vitesse Dark (dark).
  static const ShikiTheme vitesseDark = t_vitesse_dark.vitesseDark;

  /// Vitesse Light (light).
  static const ShikiTheme vitesseLight = t_vitesse_light.vitesseLight;

  // CAUTION: referencing `all` pulls EVERY theme into your build.
  // Prefer individual members.
  /// Every bundled theme. Referencing this pulls all of them into your build;
  /// prefer individual members (e.g. [andromeeda]) to keep unused themes
  /// tree-shaken out.
  static const List<ShikiTheme> all = [
    andromeeda,
    auroraX,
    ayuDark,
    ayuLight,
    ayuMirage,
    catppuccinFrappe,
    catppuccinLatte,
    catppuccinMacchiato,
    catppuccinMocha,
    darkPlus,
    dracula,
    draculaSoft,
    everforestDark,
    everforestLight,
    githubDark,
    githubDarkDefault,
    githubDarkDimmed,
    githubDarkHighContrast,
    githubLight,
    githubLightDefault,
    githubLightHighContrast,
    gruvboxDarkHard,
    gruvboxDarkMedium,
    gruvboxDarkSoft,
    gruvboxLightHard,
    gruvboxLightMedium,
    gruvboxLightSoft,
    horizon,
    horizonBright,
    houston,
    kanagawaDragon,
    kanagawaLotus,
    kanagawaWave,
    laserwave,
    lightPlus,
    materialTheme,
    materialThemeDarker,
    materialThemeLighter,
    materialThemeOcean,
    materialThemePalenight,
    minDark,
    minLight,
    monokai,
    nightOwl,
    nightOwlLight,
    nord,
    oneDarkPro,
    oneLight,
    plastic,
    poimandres,
    red,
    rosePine,
    rosePineDawn,
    rosePineMoon,
    slackDark,
    slackOchin,
    snazzyLight,
    solarizedDark,
    solarizedLight,
    synthwave84,
    tokyoNight,
    vesper,
    vitesseBlack,
    vitesseDark,
    vitesseLight,
  ];
}
