// GENERATED by tool/generate_bundled.dart. Do not edit.
//
// Importing this file pulls EVERY bundled theme into your build.
import '../src/bundled/bundled_theme.dart';
import 'andromeeda.dart';
import 'aurora_x.dart';
import 'ayu_dark.dart';
import 'ayu_light.dart';
import 'ayu_mirage.dart';
import 'catppuccin_frappe.dart';
import 'catppuccin_latte.dart';
import 'catppuccin_macchiato.dart';
import 'catppuccin_mocha.dart';
import 'dark_plus.dart';
import 'dracula_soft.dart';
import 'dracula.dart';
import 'everforest_dark.dart';
import 'everforest_light.dart';
import 'github_dark_default.dart';
import 'github_dark_dimmed.dart';
import 'github_dark_high_contrast.dart';
import 'github_dark.dart';
import 'github_light_default.dart';
import 'github_light_high_contrast.dart';
import 'github_light.dart';
import 'gruvbox_dark_hard.dart';
import 'gruvbox_dark_medium.dart';
import 'gruvbox_dark_soft.dart';
import 'gruvbox_light_hard.dart';
import 'gruvbox_light_medium.dart';
import 'gruvbox_light_soft.dart';
import 'horizon_bright.dart';
import 'horizon.dart';
import 'houston.dart';
import 'kanagawa_dragon.dart';
import 'kanagawa_lotus.dart';
import 'kanagawa_wave.dart';
import 'laserwave.dart';
import 'light_plus.dart';
import 'material_theme_darker.dart';
import 'material_theme_lighter.dart';
import 'material_theme_ocean.dart';
import 'material_theme_palenight.dart';
import 'material_theme.dart';
import 'min_dark.dart';
import 'min_light.dart';
import 'monokai.dart';
import 'night_owl_light.dart';
import 'night_owl.dart';
import 'nord.dart';
import 'one_dark_pro.dart';
import 'one_light.dart';
import 'plastic.dart';
import 'poimandres.dart';
import 'red.dart';
import 'rose_pine_dawn.dart';
import 'rose_pine_moon.dart';
import 'rose_pine.dart';
import 'slack_dark.dart';
import 'slack_ochin.dart';
import 'snazzy_light.dart';
import 'solarized_dark.dart';
import 'solarized_light.dart';
import 'synthwave_84.dart';
import 'tokyo_night.dart';
import 'vesper.dart';
import 'vitesse_black.dart';
import 'vitesse_dark.dart';
import 'vitesse_light.dart';

/// Every bundled theme.
final List<BundledTheme> allThemes = [
  andromeeda,
  auroraX,
  ayuDark,
  ayuLight,
  ayuMirage,
  catppuccinFrappe,
  catppuccinLatte,
  catppuccinMacchiato,
  catppuccinMocha,
  darkPlus,
  draculaSoft,
  dracula,
  everforestDark,
  everforestLight,
  githubDarkDefault,
  githubDarkDimmed,
  githubDarkHighContrast,
  githubDark,
  githubLightDefault,
  githubLightHighContrast,
  githubLight,
  gruvboxDarkHard,
  gruvboxDarkMedium,
  gruvboxDarkSoft,
  gruvboxLightHard,
  gruvboxLightMedium,
  gruvboxLightSoft,
  horizonBright,
  horizon,
  houston,
  kanagawaDragon,
  kanagawaLotus,
  kanagawaWave,
  laserwave,
  lightPlus,
  materialThemeDarker,
  materialThemeLighter,
  materialThemeOcean,
  materialThemePalenight,
  materialTheme,
  minDark,
  minLight,
  monokai,
  nightOwlLight,
  nightOwl,
  nord,
  oneDarkPro,
  oneLight,
  plastic,
  poimandres,
  red,
  rosePineDawn,
  rosePineMoon,
  rosePine,
  slackDark,
  slackOchin,
  snazzyLight,
  solarizedDark,
  solarizedLight,
  synthwave84,
  tokyoNight,
  vesper,
  vitesseBlack,
  vitesseDark,
  vitesseLight,
];
