name: shiki_flutter_website

description: "Showcase website for the shiki_flutter package."

publish_to: none

version: 1.0.0+1

resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  shiki_flutter:
    path: ../packages/shiki_flutter

  go_router: ^17.3.0
  url_launcher: ^6.3.2
  simple_icons: ^16.23.0

  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-400.ttf
          weight: 400
        - asset: assets/fonts/Geist-500.ttf
          weight: 500
        - asset: assets/fonts/Geist-600.ttf
          weight: 600
        - asset: assets/fonts/Geist-700.ttf
          weight: 700
    - family: Geist Mono
      fonts:
        - asset: assets/fonts/GeistMono-400.ttf
          weight: 400
        - asset: assets/fonts/GeistMono-500.ttf
          weight: 500
        - asset: assets/fonts/GeistMono-700.ttf
          weight: 700
