// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../src/bundled/bundled_language.dart';
import 'html.dart';
import 'angular_expression.dart';
import 'angular_let_declaration.dart';
import 'angular_template.dart';
import 'angular_template_blocks.dart';

/// TextMate grammar for `angular-html` (scope `text.html.derivative.ng`).
final angularHtml = BundledLanguage(
  id: 'angular-html',
  scopeName: 'text.html.derivative.ng',
  json: _json,
  embeddedLanguages: () => [
    html,
    angularExpression,
    angularLetDeclaration,
    angularTemplate,
    angularTemplateBlocks,
  ],
);

const _json =
    '{"displayName":"Angular HTML","injections":{"R:text.html - (comment.block, text.html meta.embedded, meta.tag.*.*.html, meta.tag.*.*.*.html, meta.tag.*.*.*.*.html)":{"patterns":[{"match":"<","name":"invalid.illegal.bad-angle-bracket.html"}]}},"name":"angular-html","patterns":[{"include":"text.html.basic#core-minus-invalid"},{"begin":"(</?)(\\\\w[^>\\\\s]*)(?<!/)","beginCaptures":{"1":{"name":"punctuation.definition.tag.begin.html"},"2":{"name":"entity.name.tag.html"}},"end":"((?: ?/)?>)","endCaptures":{"1":{"name":"punctuation.definition.tag.end.html"}},"name":"meta.tag.other.unrecognized.html.derivative","patterns":[{"include":"text.html.basic#attribute"}]}],"scopeName":"text.html.derivative.ng","embeddedLangs":["html","angular-expression","angular-let-declaration","angular-template","angular-template-blocks"]}';
