// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../src/bundled/bundled_language.dart';

/// TextMate grammar for `codeowners` (scope `text.codeowners`).
final codeowners = BundledLanguage(
  id: 'codeowners',
  scopeName: 'text.codeowners',
  json: _json,
);

const _json =
    '{"displayName":"CODEOWNERS","name":"codeowners","patterns":[{"include":"#comment"},{"include":"#pattern"},{"include":"#owner"}],"repository":{"comment":{"patterns":[{"begin":"^\\\\s*#","captures":{"0":{"name":"punctuation.definition.comment.codeowners"}},"end":"\$","name":"comment.line.codeowners"}]},"owner":{"match":"\\\\S*@\\\\S+","name":"storage.type.function.codeowners"},"pattern":{"match":"^\\\\s*(\\\\S+)","name":"variable.other.codeowners"}},"scopeName":"text.codeowners"}';
