// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../src/bundled/bundled_language.dart';
import 'typescript.dart';
import 'es_tag_css.dart';
import 'es_tag_glsl.dart';
import 'es_tag_html.dart';
import 'es_tag_sql.dart';
import 'es_tag_xml.dart';

/// TextMate grammar for `ts-tags` (scope `source.ts.tags`).
final tsTags = BundledLanguage(
  id: 'ts-tags',
  scopeName: 'source.ts.tags',
  json: _json,
  embeddedLanguages: () => [
    typescript,
    esTagCss,
    esTagGlsl,
    esTagHtml,
    esTagSql,
    esTagXml,
  ],
);

const _json =
    '{"displayName":"TypeScript with Tags","name":"ts-tags","patterns":[{"include":"source.ts"}],"scopeName":"source.ts.tags","embeddedLangs":["typescript","es-tag-css","es-tag-glsl","es-tag-html","es-tag-sql","es-tag-xml"],"aliases":["lit"]}';
