// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../src/bundled/bundled_language.dart';

/// TextMate grammar for `vue-directives` (scope `vue.directives`).
final vueDirectives = BundledLanguage(
  id: 'vue-directives',
  scopeName: 'vue.directives',
  json: _json,
);

const _json =
    '{"fileTypes":[],"injectTo":["source.vue","text.html.markdown","text.html.derivative","text.pug"],"injectionSelector":"L:meta.tag -meta.attribute -meta.ng-binding -entity.name.tag.pug -attribute_value -source.tsx -source.js.jsx, L:meta.element -meta.attribute","name":"vue-directives","patterns":[{"include":"text.html.vue#vue-directives"}],"scopeName":"vue.directives"}';
