// GENERATED by tool/generate_bundled.dart. Do not edit.
//
// Importing this file pulls EVERY bundled grammar into your
// build (defeats tree-shaking). Prefer importing only the
// specific `langs/<id>.dart` files you use.
import '../src/bundled/bundled_language.dart';
import 'abap.dart';
import 'actionscript_3.dart';
import 'ada.dart';
import 'angular_expression.dart';
import 'angular_html.dart';
import 'angular_inline_style.dart';
import 'angular_inline_template.dart';
import 'angular_let_declaration.dart';
import 'angular_template_blocks.dart';
import 'angular_template.dart';
import 'angular_ts.dart';
import 'apache.dart';
import 'apex.dart';
import 'apl.dart';
import 'applescript.dart';
import 'ara.dart';
import 'asciidoc.dart';
import 'asm.dart';
import 'astro.dart';
import 'awk.dart';
import 'ballerina.dart';
import 'bat.dart';
import 'beancount.dart';
import 'berry.dart';
import 'bibtex.dart';
import 'bicep.dart';
import 'bird2.dart';
import 'blade.dart';
import 'bsl.dart';
import 'c.dart';
import 'c3.dart';
import 'cadence.dart';
import 'cairo.dart';
import 'clarity.dart';
import 'clojure.dart';
import 'cmake.dart';
import 'cobol.dart';
import 'codeowners.dart';
import 'codeql.dart';
import 'coffee.dart';
import 'common_lisp.dart';
import 'coq.dart';
import 'cpp_macro.dart';
import 'cpp.dart';
import 'crystal.dart';
import 'csharp.dart';
import 'css.dart';
import 'csv.dart';
import 'cue.dart';
import 'cypher.dart';
import 'd.dart';
import 'dart.dart';
import 'dax.dart';
import 'desktop.dart';
import 'diff.dart';
import 'docker.dart';
import 'dotenv.dart';
import 'dream_maker.dart';
import 'edge.dart';
import 'elixir.dart';
import 'elm.dart';
import 'emacs_lisp.dart';
import 'erb.dart';
import 'erlang.dart';
import 'es_tag_css.dart';
import 'es_tag_glsl.dart';
import 'es_tag_html.dart';
import 'es_tag_sql.dart';
import 'es_tag_xml.dart';
import 'fennel.dart';
import 'fish.dart';
import 'fluent.dart';
import 'fortran_fixed_form.dart';
import 'fortran_free_form.dart';
import 'fsharp.dart';
import 'gdresource.dart';
import 'gdscript.dart';
import 'gdshader.dart';
import 'genie.dart';
import 'gherkin.dart';
import 'git_commit.dart';
import 'git_rebase.dart';
import 'gleam.dart';
import 'glimmer_js.dart';
import 'glimmer_ts.dart';
import 'glsl.dart';
import 'gn.dart';
import 'gnuplot.dart';
import 'go.dart';
import 'graphql.dart';
import 'groovy.dart';
import 'hack.dart';
import 'haml.dart';
import 'handlebars.dart';
import 'haskell.dart';
import 'haxe.dart';
import 'hcl.dart';
import 'hjson.dart';
import 'hlsl.dart';
import 'html_derivative.dart';
import 'html.dart';
import 'http.dart';
import 'hurl.dart';
import 'hxml.dart';
import 'hy.dart';
import 'imba.dart';
import 'ini.dart';
import 'java.dart';
import 'javascript.dart';
import 'jinja_html.dart';
import 'jinja.dart';
import 'jison.dart';
import 'json.dart';
import 'json5.dart';
import 'jsonc.dart';
import 'jsonl.dart';
import 'jsonnet.dart';
import 'jssm.dart';
import 'jsx.dart';
import 'julia.dart';
import 'just.dart';
import 'kdl.dart';
import 'kotlin.dart';
import 'kusto.dart';
import 'latex.dart';
import 'lean.dart';
import 'less.dart';
import 'liquid.dart';
import 'llvm.dart';
import 'log.dart';
import 'logo.dart';
import 'lua.dart';
import 'luau.dart';
import 'make.dart';
import 'markdown_nix.dart';
import 'markdown_vue.dart';
import 'markdown.dart';
import 'marko.dart';
import 'matlab.dart';
import 'mdc.dart';
import 'mdx.dart';
import 'mermaid.dart';
import 'mipsasm.dart';
import 'mojo.dart';
import 'moonbit.dart';
import 'move.dart';
import 'narrat.dart';
import 'nextflow_groovy.dart';
import 'nextflow.dart';
import 'nginx.dart';
import 'nim.dart';
import 'nix.dart';
import 'nushell.dart';
import 'objective_c.dart';
import 'objective_cpp.dart';
import 'ocaml.dart';
import 'odin.dart';
import 'openscad.dart';
import 'pascal.dart';
import 'perl.dart';
import 'php.dart';
import 'pkl.dart';
import 'plsql.dart';
import 'po.dart';
import 'polar.dart';
import 'postcss.dart';
import 'powerquery.dart';
import 'powershell.dart';
import 'prisma.dart';
import 'prolog.dart';
import 'proto.dart';
import 'pug.dart';
import 'puppet.dart';
import 'purescript.dart';
import 'python.dart';
import 'qml.dart';
import 'qmldir.dart';
import 'qss.dart';
import 'r.dart';
import 'racket.dart';
import 'raku.dart';
import 'razor.dart';
import 'reg.dart';
import 'regexp.dart';
import 'rel.dart';
import 'riscv.dart';
import 'ron.dart';
import 'rosmsg.dart';
import 'rst.dart';
import 'ruby.dart';
import 'rust.dart';
import 'sas.dart';
import 'sass.dart';
import 'scala.dart';
import 'scheme.dart';
import 'scss.dart';
import 'sdbl.dart';
import 'shaderlab.dart';
import 'shellscript.dart';
import 'shellsession.dart';
import 'smalltalk.dart';
import 'solidity.dart';
import 'soy.dart';
import 'sparql.dart';
import 'splunk.dart';
import 'sql.dart';
import 'ssh_config.dart';
import 'stata.dart';
import 'stylus.dart';
import 'surrealql.dart';
import 'svelte.dart';
import 'swift.dart';
import 'system_verilog.dart';
import 'systemd.dart';
import 'talonscript.dart';
import 'tasl.dart';
import 'tcl.dart';
import 'templ.dart';
import 'terraform.dart';
import 'tex.dart';
import 'toml.dart';
import 'ts_tags.dart';
import 'tsv.dart';
import 'tsx.dart';
import 'turtle.dart';
import 'twig.dart';
import 'typescript.dart';
import 'typespec.dart';
import 'typst.dart';
import 'v.dart';
import 'vala.dart';
import 'vb.dart';
import 'verilog.dart';
import 'vhdl.dart';
import 'viml.dart';
import 'vue_directives.dart';
import 'vue_html.dart';
import 'vue_interpolations.dart';
import 'vue_sfc_style_variable_injection.dart';
import 'vue_vine.dart';
import 'vue.dart';
import 'vyper.dart';
import 'wasm.dart';
import 'wenyan.dart';
import 'wgsl.dart';
import 'wikitext.dart';
import 'wit.dart';
import 'wolfram.dart';
import 'xml.dart';
import 'xsl.dart';
import 'yaml.dart';
import 'zenscript.dart';
import 'zig.dart';

/// Every bundled language.
final List<BundledLanguage> allLanguages = [
  abap,
  actionscript3,
  ada,
  angularExpression,
  angularHtml,
  angularInlineStyle,
  angularInlineTemplate,
  angularLetDeclaration,
  angularTemplateBlocks,
  angularTemplate,
  angularTs,
  apache,
  apex,
  apl,
  applescript,
  ara,
  asciidoc,
  asm,
  astro,
  awk,
  ballerina,
  bat,
  beancount,
  berry,
  bibtex,
  bicep,
  bird2,
  blade,
  bsl,
  c,
  c3,
  cadence,
  cairo,
  clarity,
  clojure,
  cmake,
  cobol,
  codeowners,
  codeql,
  coffee,
  commonLisp,
  coq,
  cppMacro,
  cpp,
  crystal,
  csharp,
  css,
  csv,
  cue,
  cypher,
  d,
  dart,
  dax,
  desktop,
  diff,
  docker,
  dotenv,
  dreamMaker,
  edge,
  elixir,
  elm,
  emacsLisp,
  erb,
  erlang,
  esTagCss,
  esTagGlsl,
  esTagHtml,
  esTagSql,
  esTagXml,
  fennel,
  fish,
  fluent,
  fortranFixedForm,
  fortranFreeForm,
  fsharp,
  gdresource,
  gdscript,
  gdshader,
  genie,
  gherkin,
  gitCommit,
  gitRebase,
  gleam,
  glimmerJs,
  glimmerTs,
  glsl,
  gn,
  gnuplot,
  go,
  graphql,
  groovy,
  hack,
  haml,
  handlebars,
  haskell,
  haxe,
  hcl,
  hjson,
  hlsl,
  htmlDerivative,
  html,
  http,
  hurl,
  hxml,
  hy,
  imba,
  ini,
  java,
  javascript,
  jinjaHtml,
  jinja,
  jison,
  json,
  json5,
  jsonc,
  jsonl,
  jsonnet,
  jssm,
  jsx,
  julia,
  just,
  kdl,
  kotlin,
  kusto,
  latex,
  lean,
  less,
  liquid,
  llvm,
  log,
  logo,
  lua,
  luau,
  make,
  markdownNix,
  markdownVue,
  markdown,
  marko,
  matlab,
  mdc,
  mdx,
  mermaid,
  mipsasm,
  mojo,
  moonbit,
  move,
  narrat,
  nextflowGroovy,
  nextflow,
  nginx,
  nim,
  nix,
  nushell,
  objectiveC,
  objectiveCpp,
  ocaml,
  odin,
  openscad,
  pascal,
  perl,
  php,
  pkl,
  plsql,
  po,
  polar,
  postcss,
  powerquery,
  powershell,
  prisma,
  prolog,
  proto,
  pug,
  puppet,
  purescript,
  python,
  qml,
  qmldir,
  qss,
  r,
  racket,
  raku,
  razor,
  reg,
  regexp,
  rel,
  riscv,
  ron,
  rosmsg,
  rst,
  ruby,
  rust,
  sas,
  sass,
  scala,
  scheme,
  scss,
  sdbl,
  shaderlab,
  shellscript,
  shellsession,
  smalltalk,
  solidity,
  soy,
  sparql,
  splunk,
  sql,
  sshConfig,
  stata,
  stylus,
  surrealql,
  svelte,
  swift,
  systemVerilog,
  systemd,
  talonscript,
  tasl,
  tcl,
  templ,
  terraform,
  tex,
  toml,
  tsTags,
  tsv,
  tsx,
  turtle,
  twig,
  typescript,
  typespec,
  typst,
  v,
  vala,
  vb,
  verilog,
  vhdl,
  viml,
  vueDirectives,
  vueHtml,
  vueInterpolations,
  vueSfcStyleVariableInjection,
  vueVine,
  vue,
  vyper,
  wasm,
  wenyan,
  wgsl,
  wikitext,
  wit,
  wolfram,
  xml,
  xsl,
  yaml,
  zenscript,
  zig,
];
