// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../src/bundled/bundled_language.dart';
import 'angular_expression.dart';

/// TextMate grammar for `angular-let-declaration` (scope `template.let.ng`).
final angularLetDeclaration = BundledLanguage(
  id: 'angular-let-declaration',
  scopeName: 'template.let.ng',
  json: _json, embeddedLanguages: () => [angularExpression],
);

const _json = '{"injectTo":["text.html.derivative","text.html.derivative.ng","source.ts.ng"],"injectionSelector":"L:text.html -comment -expression.ng -meta.tag -source.css -source.js","name":"angular-let-declaration","patterns":[{"include":"#letDeclaration"}],"repository":{"letDeclaration":{"begin":"(@let)\\\\s+([\$_[:alpha:]][\$_[:alnum:]]*)\\\\s*(=)?","beginCaptures":{"1":{"name":"storage.type.ng"},"2":{"name":"variable.other.constant.ng"},"3":{"name":"keyword.operator.assignment.ng"}},"end":"(?<=;)","name":"meta.definition.variable.ng","patterns":[{"include":"#letInitializer"}]},"letInitializer":{"begin":"\\\\s*","beginCaptures":{"0":{"name":"keyword.operator.assignment.ng"}},"contentName":"meta.definition.variable.initializer.ng","end":";","endCaptures":{"0":{"name":"punctuation.terminator.statement.ng"}},"patterns":[{"include":"expression.ng"}]}},"scopeName":"template.let.ng","embeddedLangs":["angular-expression"]}';
