// GENERATED by tool/generate_bundled.dart. Do not edit.
import '../src/bundled/bundled_language.dart';
import 'html.dart';

/// TextMate grammar for `jinja-html` (scope `text.html.jinja`).
final jinjaHtml = BundledLanguage(
  id: 'jinja-html',
  scopeName: 'text.html.jinja',
  json: _json, embeddedLanguages: () => [html],
);

const _json = '{"displayName":"jinja-html","firstLineMatch":"^\\\\{% extends [\\"\'][^\\"\']+[\\"\'] %}","foldingStartMarker":"(<(?i:(head|table|tr|div|style|script|ul|ol|form|dl))\\\\b.*?>|\\\\{%\\\\s*(block|filter|for|if|macro|raw))","foldingStopMarker":"(</(?i:(head|table|tr|div|style|script|ul|ol|form|dl))\\\\b.*?>|\\\\{%\\\\s*(end(?:block|filter|for|if|macro|raw))\\\\s*%})","name":"jinja-html","patterns":[{"include":"source.jinja"},{"include":"text.html.basic"}],"scopeName":"text.html.jinja","embeddedLangs":["html"]}';
